### PR TITLE
Fix #64 for single bind params

### LINKED ISSUE #64: bindParam using wrong number when using ? in statement
### bindParam using wrong param number when using ?

When you try to bind params with ? the first one should be 1 not 0.

### Code snippet of problem

```php
$stmt = $this->con->prepare('INSERT INTO person (name) VALUES (?)');
$var = 'Joop';
$stmt->bindParam(1, $var, PDO::PARAM_STR);
```

### PR DESCRIPTION
**Pull request by istaveren**
Fix for issue #64 

Including tests to prove it works.

### CODE REVIEW

**Comment by yajra** [comment]
Please fix the conflicts and will check again. Thanks!

**Comment by istaveren** [comment]
No problem, done.

**Comment by yajra** [comment]
Checked this and it's not working well with my other package [laravel-oci8](https://github.com/yajra/laravel-oci8). Need to dig this further.

**Comment by yajra** [comment]
Was able to get this working with a related PR https://github.com/yajra/laravel-oci8/pull/505. Will test on some other cases that I might have just to be sure before releasing. Thanks!

**Comment by istaveren** [comment]
Can this be merged?

**Comment by yajra** [comment]
Releasing on v2.0 just to be sure it will not break any existing laravel apps. Just in time for new Laravel 6 version too to bump. 

Thanks and sorry for the delays.

**Pull request merged**
