### PR TITLE
feat: add support for PHP8.4

### PR DESCRIPTION
**Pull request by danielrona**
With PHP 8.4 introducing PDO Subclasses and a new [connect function](https://wiki.php.net/rfc/pdo_driver_specific_subclasses).
I had to rename this to not crash on 8.4

[[11.x] Add PDO subclass support for PHP 8.4 #52538](https://github.com/laravel/framework/pull/52538)

### CODE REVIEW

**Comment by yajra** [comment]
Thanks for the PR. I need to set up a PHP8.4 environment and will test this along with the [Laravel OCI8](https://github.com/yajra/laravel-oci8/) package.

**Comment by shufo** [comment]
I had the same issue on PHP 8.4.1.

```bash
⬢ [Docker] ❯ php -v
PHP 8.4.1 (cli) (built: Nov 21 2024 17:57:55) (NTS)
Copyright (c) The PHP Group
Built by https://github.com/docker-library/php
Zend Engine v4.4.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies

> DB::connection('oracle')
{
	"message": "Cannot make static method PDO::connect() non static in class Yajra\\Pdo\\Oci8",
	"context": {
		"exception": {
			"class": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
			"message": "Cannot make static method PDO::connect() non static in class Yajra\\Pdo\\Oci8",
			"code": 0,
			"file": "/app/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8.php:136"
		}
	},
	"level": 400,
	"level_name": "ERROR",
	"channel": "local",
	"datetime": "2024-12-14T05:29:25.054917+09:00",
	"extra": {}
}
```

Works perfectly by this PR's fix.

```php
> DB::connection('oracle')->table('emp')->get()
= Illuminate\Support\Collection {#6560
    all: [
      {#6548
        +"empno": "aaa",
        +"empname": "test",
        +"gender_f": "0",
      },
    ],
  }

```

**Comment by shufo** [comment]
@danielrona 
Plus above, adding 8.4 test to https://github.com/yajra/pdo-via-oci8/blob/3.0/.github/workflows/continuous-integration.yml might be better.

**Comment by yajra** [comment]
Unfortunately, I am not yet able to set up a php8.4 due to some constraints.

Given @shufo's review, I think this is good for a release. But it would be nice if we could include php8.3 and 8.4 in the CI matrix. Can we add try and add it in the matrix @danielrona?

Thanks!

**Comment by danielrona** [comment]
@yajra this should do the trick i guess.

**Comment by yajra** [comment]
Released on https://github.com/yajra/pdo-via-oci8/releases/tag/v3.6.0 🚀 Thanks!

**Pull request merged**
