### PR TITLE
Changed to LONG type because number type can not be registered normally

### PR DESCRIPTION
**Pull request by reo0306**

### CODE REVIEW

**Comment by yajra** [comment]
@reo0306 thanks! Can you please provide some snippets to show what the PR fixes?

**Comment by reo0306** [comment]
ok。

■environment
OS：Windows7
DB:OracleXE
PHP:5.6
Laravel:5.4

■OracleXE
CREATE TABLE members
(
        id number NOT NULL PRIMARY KEY USING INDEX,
        name nvarchar2(40) NOT NULL,
        age number,
        email nvarchar2(255) NOT NULL,
        "password" nvarchar2(255) NOT NULL,
        remember_token nvarchar2(60),
        created_at date,
        updated_at date,
        deleted_at date
);

■What I want to solve
success：age => 0
error：  age => 4294967296

■SQLT_INT
Member::create(
                [
                        'name' => 'sample',
                        'age' => 0,
                        'email' => 'test@example.com',
                        'password' => '***********'
                ]
        );
$m = Member::find(1)->toArray();

var_dump($m);

array 
  'id' => int 1
  'name' => string 'sample'
  'age' => int 4294967296
  'email' => string 'test@example.com'
  'password' => string '***********'
  'created_at' => string '2017-06-08 00:00:00'
  'updated_at' => string '2017-06-08 00:00:00'
  'deleted_at' => null

■SQLT_LNG
Member::create(
                [
                        'name' => 'sample',
                        'age' => 0,
                        'email' => 'test@example.com',
                        'password' => '***********'
                ]
        );

$m = Member::find(1)->toArray();

var_dump($m);

array (size=11)
  'id' => int 1
  'name' => string 'sample'
  'age' => int 0
  'email' => string 'test@example.com'
  'password' => string '***********'
  'created_at' => string '2017-06-08 00:00:00'
  'updated_at' => string '2017-06-08 00:00:00'
  'deleted_at' => null

**Comment by yajra** [comment]
Sorry for overlooking this PR. Released on v1.3.4, thanks a lot!

**Comment by reo0306** [comment]
Thank you for the merge!
I am very happy.

I am saved very much by developing it.
Please continue your hard work.

**Pull request merged**
